### ISSUE TITLE
Create a single installer for the Gravatar connector for Outlook

### ISSUE THREAD

**Issue by ssbarnea** [02strich/Gravatar-Outlook-Adapter#1]
Current installation method is too complex for the "average" Outlook user, this great product needs a single file installer, for both 32bit/64bit versions.

**Comment by 02strich** [comment]
Thanks for the positive feedback :) I will work on that as soon as my current project is finished

**Comment by 02strich** [comment]
Oh I had totally forgotten how complex this was. Now there is a release to be downloaded which contains all files and a simple cmd file to run to install this - making it way easier.
