### ISSUE TITLE
install error: Unable to locate input assembly 'GravatarOSC.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by jakemonO** [02strich/Gravatar-Outlook-Adapter#2]
Install (32 bit) throws error: RegAsm : error RA0000 : Unable to locate input assembly 'GravatarOSC.dll' or one of its dependencies.

I don't see GravatarOSC.dll in the download at all

**Comment by nstoeckigt** [comment]
I also first had to realise that...

> Fork of http://gravatarnet.codeplex.com to better up the code and incorporate Gravatar profile support.

so you have to download the appropriate DLL there (http://gravatarnet.codeplex.com/releases/view/48712)

**Comment by 02strich** [comment]
If you download the repository you only get the source files and scripts. In order to get the GravartarOSC.dll you need to compile the sources using Visual Studio first and then run the installation script.
