### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by alejofonseca** [02strich/Gravatar-Outlook-Adapter#3]
Hi All,

I've been trying to get outlook 2013 to work with gravatar, with no success. Found out this git, downloaded it, run the installer and nothing happened. 

Can anyone please let me know how it works?

Thanks in advance.

Alejandro.

**Comment by 02strich** [comment]
Hi,

I am sorry, but I have actually never tested the plugin with Outlook 2013. If I get some time this weekend I will give it a try and update the installer accordingly.

**Comment by jakemonO** [comment]
Outlook 2010 32-bit, downloaded the installer and ran the 32 bit install. Restarted Outlook. Don;t see it in the add-ins. Am I missing something? TIA.

**Comment by 02strich** [comment]
Is this still an open question?

**Comment by alejofonseca** [comment]
I believe you can close it up, thx.

**Comment by 02strich** [comment]
Which installer did you run and did you see any error messages?

The Install32|64.cmd require that you compile the source code using Visual Studio first before running the scripts.

**Comment by 02strich** [comment]
I have created a first release of this repo which contains all the code needed. This should make the installation way simpler :)
